//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class par_emp
    {
        public string cod_emp { get; set; }
        public int tab_num { get; set; }
        public byte[] logo { get; set; }
        public System.DateTime fecha_res { get; set; }
        public string temp_char1 { get; set; }
        public string temp_char2 { get; set; }
        public string temp_char3 { get; set; }
        public string temp_char4 { get; set; }
        public string temp_char5 { get; set; }
        public string temp_char6 { get; set; }
        public string temp_char7 { get; set; }
        public string temp_char8 { get; set; }
        public System.DateTime temp_fech { get; set; }
        public int temp_num { get; set; }
        public string emp_adm { get; set; }
        public string emp_cont { get; set; }
        public string emp_nom { get; set; }
        public string urlservidorweb_admin { get; set; }
        public string urlservidorweb_cont { get; set; }
        public string urlservidorweb_nom { get; set; }
        public string tipo_imp_prov_ext { get; set; }
        public bool netTcp_admin { get; set; }
        public bool netTcp_cont { get; set; }
        public bool netTcp_nom { get; set; }
        public string login_admin { get; set; }
        public string password_admin { get; set; }
        public string login_cont { get; set; }
        public string password_cont { get; set; }
        public string login_nom { get; set; }
        public string password_nom { get; set; }
        public System.DateTime fec_cont { get; set; }
        public string co_cue_aju { get; set; }
        public int tempor1 { get; set; }
        public string g_moneda { get; set; }
        public bool g_mostrar_modelo { get; set; }
        public int g_alerta_f { get; set; }
        public bool p_desc_art { get; set; }
        public bool p_desc_cat { get; set; }
        public bool p_desc_glo { get; set; }
        public bool p_desc_lin { get; set; }
        public bool v_redondeo { get; set; }
        public int v_tipo_redondeo { get; set; }
        public string v_valor_redondeo { get; set; }
        public bool c_redondeo { get; set; }
        public int c_tipo_redondeo { get; set; }
        public string c_valor_redondeo { get; set; }
        public bool v_maneja_sucursales { get; set; }
        public bool v_concepto_despacho { get; set; }
        public bool v_manejo_direccion_entrega { get; set; }
        public string v_tip_cli { get; set; }
        public string v_co_ven { get; set; }
        public string v_cond_pago { get; set; }
        public string v_cta_ing_egr { get; set; }
        public string v_co_seg { get; set; }
        public string v_co_zon { get; set; }
        public string v_tipo_per { get; set; }
        public bool i_stock_negativo_advertencia { get; set; }
        public bool i_stock_negativo { get; set; }
        public int i_dec_stock { get; set; }
        public int i_dec_costo { get; set; }
        public int i_dec_precio { get; set; }
        public bool i_multiple_moneda { get; set; }
        public string i_moneda_articulo { get; set; }
        public bool i_seriales_articulo { get; set; }
        public bool i_licores { get; set; }
        public int i_tipo_cost_dev { get; set; }
        public bool i_maneja_lotes_vencidos { get; set; }
        public int i_costo_inventario { get; set; }
        public bool i_permitir_fec_menor_ult_inv { get; set; }
        public Nullable<int> i_manejo_art_comp { get; set; }
        public bool c_margen_costo_precio { get; set; }
        public string c_tip_pro { get; set; }
        public string c_cond_pago { get; set; }
        public string c_cta_ing_egr { get; set; }
        public string c_co_seg { get; set; }
        public string c_co_zon { get; set; }
        public string c_tipo_per { get; set; }
        public bool cb_canc_comp_ord_pag { get; set; }
        public bool cb_manej_imp_tran { get; set; }
        public bool cb_impre_fis { get; set; }
        public int v_max_reng { get; set; }
        public bool v_max_reng_todos { get; set; }
        public bool lotes_despacho { get; set; }
        public bool seriales_despacho { get; set; }
        public string format1 { get; set; }
        public string format2 { get; set; }
        public string format3 { get; set; }
        public string format4 { get; set; }
        public string format5 { get; set; }
        public string co_sucur { get; set; }
        public string campo1 { get; set; }
        public string campo2 { get; set; }
        public string campo3 { get; set; }
        public string campo4 { get; set; }
        public string campo5 { get; set; }
        public string co_us_in { get; set; }
        public string co_sucu_in { get; set; }
        public System.DateTime fe_us_in { get; set; }
        public string co_us_mo { get; set; }
        public string co_sucu_mo { get; set; }
        public System.DateTime fe_us_mo { get; set; }
        public string revisado { get; set; }
        public string trasnfe { get; set; }
        public Nullable<System.Guid> rowguid { get; set; }
        public byte[] validador { get; set; }
        public Nullable<bool> imp_vend { get; set; }
        public Nullable<bool> imp_turno { get; set; }
        public Nullable<bool> imp_numfac { get; set; }
        public Nullable<bool> imp_caja { get; set; }
        public Nullable<bool> imp_suc { get; set; }
        public Nullable<bool> imp_cajero { get; set; }
        public string c_co_pais { get; set; }
        public string v_co_pais { get; set; }
        public bool cb_sujt_reten { get; set; }
        public decimal cb_reten { get; set; }
        public string tipo_imagen { get; set; }
        public Nullable<int> tamaño_imagen { get; set; }
        public string co_uni_peso { get; set; }
        public string co_uni_volumen { get; set; }
        public Nullable<int> c_reten_auto { get; set; }
        public string correoservidor { get; set; }
        public string correodir { get; set; }
        public bool correossl { get; set; }
        public int correopuerto { get; set; }
        public short correometodo_ent { get; set; }
        public short correotiempo_exp { get; set; }
        public bool correocredencial_def { get; set; }
        public string correousuario { get; set; }
        public string correopass { get; set; }
        public Nullable<int> c_retenISLR_auto { get; set; }
        public bool v_reconv { get; set; }
        public bool v_maneja_ncf { get; set; }
        public string pto_emision { get; set; }
        public string area_imp { get; set; }
    }
}
