//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MASTER
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class masterprofitEntities : DbContext
    {
        public masterprofitEntities()
            : base("name=masterprofitEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MpUsuario> MpUsuario { get; set; }
    
        public virtual ObjectResult<Nullable<int>> pAutenticarUsuario(string sUsuario, string sPassword)
        {
            var sUsuarioParameter = sUsuario != null ?
                new ObjectParameter("sUsuario", sUsuario) :
                new ObjectParameter("sUsuario", typeof(string));
    
            var sPasswordParameter = sPassword != null ?
                new ObjectParameter("sPassword", sPassword) :
                new ObjectParameter("sPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pAutenticarUsuario", sUsuarioParameter, sPasswordParameter);
        }
    }
}
