//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MASTER
{
    using System;
    using System.Collections.Generic;
    
    public partial class MpUsuario
    {
        public string Cod_Usuario { get; set; }
        public string Desc_Usuario { get; set; }
        public byte[] Password { get; set; }
        public decimal Prioridad { get; set; }
        public string Usuario_Nodo { get; set; }
        public string Id_Grupo { get; set; }
        public bool Camb_Sucu { get; set; }
        public bool Pide_Sucu { get; set; }
        public string Sucursal { get; set; }
        public string Id_Idioma { get; set; }
        public bool Pcontrol_1 { get; set; }
        public bool Pcontrol_2 { get; set; }
        public Nullable<int> Serie { get; set; }
        public System.DateTime Fec_Ult { get; set; }
        public Nullable<System.DateTime> Fec_Prox { get; set; }
        public int Veces { get; set; }
        public Nullable<System.DateTime> Fec_Ult_FA { get; set; }
        public string Estado { get; set; }
        public string Ad_Login { get; set; }
        public string Cod_Empresa { get; set; }
        public string Cod_Empresa_Nomi { get; set; }
        public string Cod_Empresa_Admi { get; set; }
        public bool Sel_Emp { get; set; }
        public bool Sel_Emp_Nomi { get; set; }
        public bool Sel_Emp_Admi { get; set; }
        public string co_mapa { get; set; }
        public string co_mapa_nomi { get; set; }
        public string co_mapa_admi { get; set; }
        public bool Acceso_Todas_Empresa { get; set; }
        public bool Acceso_Todas_Empresa_Nomi { get; set; }
        public bool Acceso_Todas_Empresa_Admi { get; set; }
        public string co_us_in { get; set; }
        public System.DateTime fe_us_in { get; set; }
        public string co_us_mo { get; set; }
        public System.DateTime fe_us_mo { get; set; }
        public string campo1 { get; set; }
        public string campo2 { get; set; }
        public string campo3 { get; set; }
        public string campo4 { get; set; }
        public string campo5 { get; set; }
        public string campo6 { get; set; }
        public string campo7 { get; set; }
        public string campo8 { get; set; }
        public string co_sucu_in { get; set; }
        public string co_sucu_mo { get; set; }
        public string revisado { get; set; }
        public string trasnfe { get; set; }
        public byte[] validador { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
